/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as MainRouteImport } from "./routes/_main"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as MainSettingsRouteImport } from "./routes/_main.settings"
import { Route as MainItemsRouteImport } from "./routes/_main.items"
import { Route as MainDashboardRouteImport } from "./routes/_main.dashboard"
import { Route as AuthRegisterRouteImport } from "./routes/_auth.register"
import { Route as AuthLoginRouteImport } from "./routes/_auth.login"
import { Route as MainItemsItemIdRouteImport } from "./routes/_main.items.$itemId"
import { Route as MainItemsItemIdEditRouteImport } from "./routes/_main.items.$itemId.edit"

const MainRoute = MainRouteImport.update({
  id: "/_main",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => MainRoute,
} as any)
const MainItemsRoute = MainItemsRouteImport.update({
  id: "/items",
  path: "/items",
  getParentRoute: () => MainRoute,
} as any)
const MainDashboardRoute = MainDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => MainRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any)
const MainItemsItemIdRoute = MainItemsItemIdRouteImport.update({
  id: "/$itemId",
  path: "/$itemId",
  getParentRoute: () => MainItemsRoute,
} as any)
const MainItemsItemIdEditRoute = MainItemsItemIdEditRouteImport.update({
  id: "/edit",
  path: "/edit",
  getParentRoute: () => MainItemsItemIdRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof AuthLoginRoute
  "/register": typeof AuthRegisterRoute
  "/dashboard": typeof MainDashboardRoute
  "/items": typeof MainItemsRouteWithChildren
  "/settings": typeof MainSettingsRoute
  "/items/$itemId": typeof MainItemsItemIdRouteWithChildren
  "/items/$itemId/edit": typeof MainItemsItemIdEditRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof AuthLoginRoute
  "/register": typeof AuthRegisterRoute
  "/dashboard": typeof MainDashboardRoute
  "/items": typeof MainItemsRouteWithChildren
  "/settings": typeof MainSettingsRoute
  "/items/$itemId": typeof MainItemsItemIdRouteWithChildren
  "/items/$itemId/edit": typeof MainItemsItemIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_auth": typeof AuthRouteWithChildren
  "/_main": typeof MainRouteWithChildren
  "/_auth/login": typeof AuthLoginRoute
  "/_auth/register": typeof AuthRegisterRoute
  "/_main/dashboard": typeof MainDashboardRoute
  "/_main/items": typeof MainItemsRouteWithChildren
  "/_main/settings": typeof MainSettingsRoute
  "/_main/items/$itemId": typeof MainItemsItemIdRouteWithChildren
  "/_main/items/$itemId/edit": typeof MainItemsItemIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/register"
    | "/dashboard"
    | "/items"
    | "/settings"
    | "/items/$itemId"
    | "/items/$itemId/edit"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/register"
    | "/dashboard"
    | "/items"
    | "/settings"
    | "/items/$itemId"
    | "/items/$itemId/edit"
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/_main"
    | "/_auth/login"
    | "/_auth/register"
    | "/_main/dashboard"
    | "/_main/items"
    | "/_main/settings"
    | "/_main/items/$itemId"
    | "/_main/items/$itemId/edit"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_main": {
      id: "/_main"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_main/settings": {
      id: "/_main/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRoute
    }
    "/_main/items": {
      id: "/_main/items"
      path: "/items"
      fullPath: "/items"
      preLoaderRoute: typeof MainItemsRouteImport
      parentRoute: typeof MainRoute
    }
    "/_main/dashboard": {
      id: "/_main/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof MainDashboardRouteImport
      parentRoute: typeof MainRoute
    }
    "/_auth/register": {
      id: "/_auth/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/login": {
      id: "/_auth/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_main/items/$itemId": {
      id: "/_main/items/$itemId"
      path: "/$itemId"
      fullPath: "/items/$itemId"
      preLoaderRoute: typeof MainItemsItemIdRouteImport
      parentRoute: typeof MainItemsRoute
    }
    "/_main/items/$itemId/edit": {
      id: "/_main/items/$itemId/edit"
      path: "/edit"
      fullPath: "/items/$itemId/edit"
      preLoaderRoute: typeof MainItemsItemIdEditRouteImport
      parentRoute: typeof MainItemsItemIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainItemsItemIdRouteChildren {
  MainItemsItemIdEditRoute: typeof MainItemsItemIdEditRoute
}

const MainItemsItemIdRouteChildren: MainItemsItemIdRouteChildren = {
  MainItemsItemIdEditRoute: MainItemsItemIdEditRoute,
}

const MainItemsItemIdRouteWithChildren = MainItemsItemIdRoute._addFileChildren(
  MainItemsItemIdRouteChildren,
)

interface MainItemsRouteChildren {
  MainItemsItemIdRoute: typeof MainItemsItemIdRouteWithChildren
}

const MainItemsRouteChildren: MainItemsRouteChildren = {
  MainItemsItemIdRoute: MainItemsItemIdRouteWithChildren,
}

const MainItemsRouteWithChildren = MainItemsRoute._addFileChildren(
  MainItemsRouteChildren,
)

interface MainRouteChildren {
  MainDashboardRoute: typeof MainDashboardRoute
  MainItemsRoute: typeof MainItemsRouteWithChildren
  MainSettingsRoute: typeof MainSettingsRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainDashboardRoute: MainDashboardRoute,
  MainItemsRoute: MainItemsRouteWithChildren,
  MainSettingsRoute: MainSettingsRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
